version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
  db-testing-store:
  vendor-store:
  node_modules-store:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./src:/var/www
      - vendor-store:/work/src/vendor

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./src:/var/www
      - node_modules-store:/work/src/node_modules

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-develop}
      - MYSQL_USER=${DB_USER:-develop}
      - MYSQL_PASSWORD=${DB_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-password}
    user: "1000:50"
    command: --innodb-use-native-aio=0

  db_testing:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3333:3306
    volumes:
      - db-testing-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=develop
      - MYSQL_USER=develop
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    user: "1000:50"
    command: --innodb-use-native-aio=0

  mail:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT:-8025}:8025